
version: '3.8'
services:
  devLive:
    container_name: crosshare-dev-live-firebase
    profiles:
      - devLive
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=../serviceAccountKey.json
    command: next dev
    build:
      context: .
      target: dev
    image: dev
    ipc: host
    volumes:
      - "./serviceAccountKey.json:/src/serviceAccountKey.json:z"
      - "./app:/src/app:z"
      - "/src/app/node_modules"
      - "/src/app/nextjs"
    working_dir: /src/app
    ports:
      - 3000:3000

  dev:
    container_name: crosshare-dev
    profiles:
      - dev
    environment:
      - NEXT_PUBLIC_USE_EMULATORS=1
      - METADATA_SERVER_DETECTION=none
      - GCE_METADATA_HOST=0.0.0.0
      - FIRESTORE_EMULATOR_HOST="127.0.0.1:8080"
      - GCLOUD_PROJECT="demo-crosshare"
    command: firebase emulators:exec --import=./emulator-data --only auth,firestore,functions,storage,pubsub --project demo-crosshare --ui 'next dev'
    build:
      context: .
      target: dev
    image: dev
    ipc: host
    volumes:
      - "./app:/src/app:z"
      - "./functions:/src/functions:z"
      - "./app/firebaseConfig.emulators.ts:/src/app/firebaseConfig.ts:z"
      - "/src/app/node_modules"
      - "/src/app/nextjs"
    working_dir: /src/app
    ports:
      - 3000:3000
      - 9199:9199
      - 9099:9099
      - 9005:9005
      - 9000:9000
      - 8085:8085
      - 8080:8080
      - 5001:5001
      - 5000:5000
      - 4500:4500
      - 4000:4000
      - 9150:9150
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s