
version: '3.8'
services:
  devLive:
    profiles:
      - devLive
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=../serviceAccountKey.json
    command: next dev
    build:
      context: .
      target: dev
    image: dev
    volumes:
      - "./serviceAccountKey.json:/src/serviceAccountKey.json:z"
      - "./app:/src/app:z"
      - "/src/app/node_modules"
      - "/src/app/nextjs"
    working_dir: /src/app
    ports:
      - 3000:3000

  dev:
    profiles:
      - dev
    environment:
      - NEXT_PUBLIC_USE_EMULATORS=1
    command: firebase emulators:exec --only auth,firestore,functions,storage,pubsub --project demo-crosshare --ui 'next dev'
    build:
      context: .
      target: dev
    image: dev
    volumes:
      - "./app:/src/app:z"
      - "./functions:/src/functions:z"
      - "./firebaseConfig.emulators.ts:/src/app/firebaseConfig.ts:z"
      - "/src/app/node_modules"
      - "/src/app/nextjs"
    working_dir: /src/app
    ports:
      - 3000:3000
      - 9199:9199
      - 9099:9099
      - 9005:9005
      - 9000:9000
      - 8085:8085
      - 8080:8080
      - 5001:5001
      - 5000:5000
      - 4500:4500
      - 4000:4000
      - 9150:9150
