name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - uses: pnpm/action-setup@v4
    - name: Install modules
      working-directory: ./app
      run: pnpm install --frozen-lockfile
    - name: Build i18n files
      working-directory: ./app
      run: pnpm compileI18n
    - name: Copy dummy fb config
      working-directory: ./app
      run: cp ./firebaseConfig.emulators.ts ./firebaseConfig.ts
    - name: Lint
      working-directory: ./app
      run: pnpm lint
    - name: Check formatting
      working-directory: ./app
      run: pnpm checkFormat
    - name: Run tests
      working-directory: ./app
      run: |
        npm install -g firebase-tools
        firebase emulators:exec --only firestore --project demo-crosshare 'NODE_OPTIONS='--experimental-vm-modules'  npx jest --ci'
