name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./app
      run: yarn
    - name: Run tests
      working-directory: ./app
      run: NODE_OPTIONS='--experimental-vm-modules'  npx jest --ci
